name: quality

on:
    pull_request:
    push:
        branches: [master]

env:
    PROJECT_ID: ${{ secrets.RUN_PROJECT }}
    RUN_REGION: asia-northeast1
    SERVICE_NAME: direktor

jobs:
    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        if: github.ref == 'refs/heads/master'
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: setup gcloud tools
              uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
              with:
                  version: "291.0.0"
                  service_account_key: ${{ secrets.SA_KEY }}
                  project_id: ${{ secrets.PROJECT_ID }}
            - name: deploy
              run: gcloud builds submit --config infrastructure/cloud-build.yml
